export const FROM_SYSTEM_MESSAGE_ADDRESS =
  process.env.FROM_SYSTEM_MESSAGE_ADDRESS!;
export const TO_SYSTEM_MESSAGE_ADDRESS = process.env.TO_SYSTEM_MESSAGE_ADDRESS!;
export const DYNAMODB_END_POINT = process.env.DYNAMODB_END_POINT!;
export const MAGIARIUM_TABLE_NAME = process.env.MAGIARIUM_TABLE_NAME!;
export const MAGIARIUM_BUCKET_NAME = process.env.MAGIARIUM_BUCKET_NAME!;
export const AWS_REGION = process.env.AWS_REGION!;
